services:
  shiny:
    build: .
    restart: unless-stopped
    expose:
      - "3838"
    volumes:
      - /srv/shiny-server:/srv/shiny-server
    networks:
      - dokploy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.pugaxtrade.rule=Host(`pugaxtrade.com`) && PathPrefix(`/pugaxtrade`)"
      - "traefik.http.routers.pugaxtrade.entrypoints=websecure"
      - "traefik.http.routers.pugaxtrade.tls=true"
      - "traefik.http.routers.pugaxtrade.priority=100"

      - "traefik.http.services.pugaxtrade.loadbalancer.server.port=3838"

      # StripPrefix: /pugaxtrade -> /
      - "traefik.http.middlewares.pugaxtrade-stripprefix.stripprefix.prefixes=/pugaxtrade"
      - "traefik.http.routers.pugaxtrade.middlewares=pugaxtrade-stripprefix"

networks:
  dokploy:
    external: true
